name: Build and Upload Videos

on:
  # 触发条件：当推送带有vX.X.X格式的tag时执行
  workflow_dispatch

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出代码仓库
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. 设置Python环境
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # 根据你的脚本需求修改版本号

    # 3. 安装依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests bs4  # 确保你有requirements.txt文件
        sudo apt update
        sudo apt install ffmpeg

    # 4. 执行Python脚本生成视频
    - name: Run video generation script
      run: |
        python 6.py 
    - name: Wait for ffmpeg to finish
      run: |
        echo "Waiting for ffmpeg processes to finish..."
        while pgrep ffmpeg > /dev/null; do
          echo "ffmpeg is still running. Waiting for 10 seconds..."
          sleep 10
        done
        echo "ffmpeg is no longer running. Proceeding with compression."
        
    # 5. 压缩res目录
    - name: Compress result folder
      run: |
        zip -r /mnt/res.zip res/  # 递归压缩res目录

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: res  # 附件名称
        path: /mnt/res.zip           # 附件路径
        if-no-files-found: error  # 如果找不到文件，抛出错误
